Add support for reporting the build status directly to the test script

diff --git a/vgci/post-report b/vgci/post-report
--- a/vgci/post-report
+++ b/vgci/post-report
@@ -212,9 +212,19 @@ cat "${MD_IN}" | sed "s|{{REPORT_URL}}|${REPORT_URL}|g" | tee processed.md
 if [ ! -z "${CI}" ]; then
     # On cloud CI, so actually post a comment
     
+    # TODO: Until we fix Gitlab integration this also is responsible for reporting the status metadata
+    
+    # Decide if we succeeded or failed
+    STATUS_STATE="failure"
+    if grep "19 tests passed" processed.md >/dev/null ; then
+        # Hackily check if the comment we are posting has all tests reporting in as successful.
+        STATUS_STATE="success"
+    fi
+    
     # Comment on the commit we built.
     # We don't have a good way to know if there is an open PR for it, and there might be more than one maybe.
-    vgci/post-comment.py vgteam/vg --in_file processed.md --commit "${CI_COMMIT_SHA}" || true 
+    vgci/post-comment.py vgteam/vg --in_file processed.md --commit "${CI_COMMIT_SHA}" \
+        --status-state "${STATUS_STATE}" --status-context "ci/gitlab/ucsc-ci.com" || true 
     
     if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then
         # Normal master build
